### ISSUE TITLE
Bug with visual representation of fractions

### ISSUE THREAD

**Issue by leonfrischauf** [centaur54dev/ckeditor5-math-preview#3]
Hi, we have implemented the plugin as described for our math community site.

Unfortunately the following issue occurs:

![2019-05-17_21-24-49](https://user-images.githubusercontent.com/1921516/57951402-3fd33f00-78ea-11e9-9669-3325c89d54c4.jpeg)

Is this known and does this only occur with the latest version?

Best, Leon

**Comment by centaur54dev** [comment]
Sorry for the delayed response. 
I haven't encountered any problem with fractions. What engine do you use, Mathjax or katex? Are you getting any console errors?

**Comment by centaur54dev** [comment]
Closed because no feedback was provided on the issue for a long time.
If the issue is still relevant please create a new one.
