### ISSUE TITLE
Doesn't work with no errors

### ISSUE THREAD

**Issue by wenisy** [centaur54dev/ckeditor5-math-preview#5]
It doesn't work with no errors.

Here are my commits `https://github.com/wenisy/ckeditor5-build-classic/commit/775e1fc398381b6d4893d77789f7f43c8a94cac2`

1. I add this plugin into `dependencies` not `devDependencies`
```json
  "dependencies": {
    "ckeditor5-math-preview": "^1.0.7"
  }
```
2. I add `MathpreviewPlugin` into `ckeditor.js`

3. Test it on python -m SimpleHTTPServer with local file No errors, no modal alert, no correct result.

![image](https://user-images.githubusercontent.com/5832130/61036860-82059200-a3fc-11e9-9b22-edf777fd5ad1.png)

There is no declaration for `mathjax` in README, so I assume it is unnecessary.

And event I added `mathjax` into dependencies, it still doesn't work.

**Comment by centaur54dev** [comment]
Have you loaded mathjax source in html? From  the [official mathjax documentation](https://www.mathjax.org/#gettingstarted) one simple way to do it is this: 
`<script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-MML-AM_CHTML' async></script>`

Of course you can configure this to your needs.

**Comment by wenisy** [comment]
I tried, but still not work.
<img width="2192" alt="image" src="https://user-images.githubusercontent.com/5832130/61192103-74922580-a6e4-11e9-8167-be41e120c7cd.png">

And I assume there would be a popup when I click on `Fx` button?

**Comment by centaur54dev** [comment]
No popup when you just click the Fx button. The button is like a switch that toggles the plugin on and off. If it is "ON", then you can expect to see popup when you click inside the formula. Does this happen?

**Comment by wenisy** [comment]
Nothing happened.

No formula, no popup. Any ideas about it according to that screenshot?

**Comment by centaur54dev** [comment]
And still no console errors? Perhaps something wrong in your stack. I have tested your commit with a simple html and it worked perfectly.
![image](https://user-images.githubusercontent.com/40833357/61209479-8d113880-a702-11e9-930e-053d70b1e9fd.png)

The html i have used is the following (`ckeditor.js` is the ckeditor.js file from your commit). I serve the file locally through xammp. 

```
<!DOCTYPE html>
<html lang="en">
<head>
</head>

<body>
	<h2>Test</h2>
	<div id="editor1"></div>

	<script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-MML-AM_CHTML' async></script>
	<script src="ckeditor.js"></script>
	<script>
		let editorDiv = document.getElementById("editor1");
		let editor = ClassicEditor
	        .create(  editorDiv )
	        .then( (editor) => {
	            console.log( "editor1 loaded succesfully");
	        } )
	        .catch( error => {	
	            console.error( error );
	        } );
	</script>
</body>
</html>
```

**Comment by wenisy** [comment]
Thanks!!!!

If it could work on your computer, I think I could figure it out by myself. 

Really thanks to you.

**Comment by centaur54dev** [comment]
Served with python SimpleHTTPServer also works the same. Very strange, i don't see anything faulty in your code.

**Comment by wenisy** [comment]
> Served with python SimpleHTTPServer also works the same. Very strange, i don't see anything faulty in your code.

With CDN mathjax?

**Comment by centaur54dev** [comment]
Yes the same html. In fact i have used: 
python2 -m SimpleHTTPServer 30000

**Comment by centaur54dev** [comment]
Test this jsfiddle...
[https://jsfiddle.net/centaur54dev/r603ey87/](https://jsfiddle.net/centaur54dev/r603ey87/)
It works for me.

**Comment by wenisy** [comment]
`Chrome below`
<img width="1277" alt="pic" src="https://user-images.githubusercontent.com/5832130/61260038-53e2d200-a7af-11e9-9409-40e23b27298d.png">
this is what happened to me... 

nothing happened...


`Firefox below`
<img width="1277" alt="pic" src="https://user-images.githubusercontent.com/5832130/61260073-74129100-a7af-11e9-871e-e8fa60e56a93.png">

**Comment by centaur54dev** [comment]
Don't select the formula. Simple click. And wait a couple of seconds.

**Comment by wenisy** [comment]
![image](https://user-images.githubusercontent.com/5832130/61341202-03837700-a878-11e9-90b4-28cd58100720.png)

Works!!!!!!!!!!!!!!

Thanks!!!!!!!!!!!!

**Comment by centaur54dev** [comment]
:) 
The issue with the wrong looking fraction occurs in jsfiddle and the python server  (maybe some css is blocked) but not in xampp or production servers. However you can overcome it if you use a different config in the mathjax script. For example instead of `config=TeX-MML-AM_CHTML` use `config=TeX-AMS_HTML`.
See the [updated jsfiddle](https://jsfiddle.net/centaur54dev/r603ey87/)

**Comment by wenisy** [comment]
Really thanks!!!!
I don't have any other questions about it for now, I'm fine if you want to close this issue.
