### ISSUE TITLE
Updating the dependencies

### ISSUE THREAD

**Issue by jakob-info** [centaur54dev/ckeditor5-math-preview#8]
Hey, i would like to use this cool plugin to write better Latex.
Sadly, it doesn't work due to duplicate modules because  of this plugin uses 20 but the ckEditor5 is already developed to version 27.

Also a Keyboard Shortcut would be pretty awesome or even better if the popup appears automatically :)

**Comment by centaur54dev** [comment]
The popup indeed appears automatically when clicking anywhere in the latex code. Dependencies should be ok now.
